name: Core
version: '${project.version}'
main: me.lagggpixel.core.Main
api-version: '1.20'
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true
    Vault:
      load: BEFORE
      required: true
    EzChestShop:
      load: AFTER
      required: false