name: Core
version: '${project.version}'
main: me.lagggpixel.core.Main
api-version: '1.20'
authors:
  - Lagggpixel (Main developer)
  - Exortions (Merchant Module original author)
  - Rapha149 (SignGUI Library)
  - ZorTik (Containr Library)
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true
    Vault:
      load: BEFORE
      required: true
    Citizens:
      load: BEFORE
      required: true
    NBTAPI:
      load: BEFORE
      required: true
    EzChestShop:
      load: AFTER
      required: false
    MyPet:
      load: AFTER
      required: false