name: Maven Build and Publish to GitHub Packages

on:
  push:
    branches:
      - main
  workflow_dispatch: # Triggered manually from GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Check Maven version
      run: |
        export JAVA_HOME="${{ env.JAVA_HOME }}"
        mvn -v

    - name: Build with Maven
      run: |
        export JAVA_HOME="${{ env.JAVA_HOME }}"
        mvn -B package --file pom.xml

    - name: Set up Maven for GitHub Packages
      run: echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > ~/.npmrc

    - name: Publish to GitHub Packages
      run: |
        export JAVA_HOME="${{ env.JAVA_HOME }}"
        mvn deploy --file pom.xml
