name: Maven Build and Publish to GitHub Packages

on:
  push:
    branches:
      - main
  workflow_dispatch: # Triggered manually from GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Check Maven version
      run: |
        export JAVA_HOME="${{ env.JAVA_HOME }}"
        mvn -v

    - name: Build with Maven
      run: |
        export JAVA_HOME="${{ env.JAVA_HOME }}"
        mvn -B package --file pom.xml

    - name: Set up Maven for GitHub Packages
      run: |
        echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
            <server>
              <id>github</id>
              <username>${{ github.actor }}</username>
              <password>${{ secrets.GITHUB_TOKEN }}</password>
            </server>
          </servers>
        </settings>' > ${{ github.workspace }}/settings.xml

    - name: Publish to GitHub Packages
      run: |
        export JAVA_HOME="${{ env.JAVA_HOME }}"
        mvn deploy --file pom.xml
